export const maps = [
    ['Bone Crypt', 'Crimson Township', 'Shipyard', 'Desert Spring'],
    [
        'Dunes',
        'Iceberg',
        'Pier',
        'Arsenal',
        'Belfry',
        'Arcade',
        'Wharf',
        'Lair',
    ],
    [
        'Overgrown Shrine',
        'Strand',
        'Volcano',
        'Crystal Ore',
        'Toxic Sewer',
        'Mausoleum',
        'Fungal Hollow',
        'Channel',
    ],
    [
        'Cemetery',
        'Moon Temple',
        'Vaal Pyramid',
        'Canyon',
        'Fields',
        'Foundry',
        'Primordial Pool',
        'Cells',
    ],
    [
        'Atoll',
        'Courtyard',
        'Graveyard',
        'Gardens',
        'Siege',
        'Burial Chambers',
        'Cage',
        'Phantasmagoria',
    ],
    [
        'Shore',
        'Promenade',
        'Dry Sea',
        'Arid Lake',
        'Waterways',
        'Tower',
        'Basilica',
    ],
    [
        'Cursed Crypt',
        'Waste Pool',
        'Silo',
        'Spider Forest',
        'Courthouse',
        'Dungeon',
        'Bramble Valley',
    ],
    [
        'Orchard',
        'Jungle Valley',
        'Lava Lake',
        'Sunken City',
        'Reef',
        'Frozen Cabins',
        'Ashen Wood',
    ],
    ['Park', 'Lookout', 'Tropical Island', 'Stagnation', 'Academy', 'Glacier'],
    [
        'Underground Sea',
        'Pit',
        'Wasteland',
        'Excavation',
        'Arachnid Nest',
        'Grotto',
    ],
    [
        'Acid Caverns',
        'Plaza',
        'Residence',
        'Sulphur Vents',
        'Forking River',
        'Conservatory',
    ],
    ['Museum', 'Necropolis', 'Barrows', 'Bog', 'Crimson Temple', 'Palace'],
    ['Flooded Mine', 'Mineral Pools', 'Terrace', 'Grave Trough', 'Shrine'],
    ['Temple', 'Maze', 'Forbidden Woods', 'Estuary', 'Defiled Cathedral'],
    ['Underground River', 'Cold River', 'Arena', 'Port', 'Vault'],
    ['Plateau', 'Lava Chamber', 'Castle Ruins', 'Thicket'],
];

export const uniqueMaps = [
    "Acton's Nightmare",
    "Wolfpack's Den",
    'Death and Taxes',
    "Doryani's",
    'Hallowed Ground',
    'Maelström',
    'Mao Kun',
    "Oba's Cursed Trove",
    "Olmec's Sanctum",
    'Pillars of Arun',
    "Poorjoy's Asylum",
    "The Coward's Trial",
    'The Putrid Cloister',
    'The Twilight Temple',
    'The Vinktar Square',
    'Vaults of Atziri',
    'Whakawairua',
];

export const allMaps = [...maps, uniqueMaps];